<?php
//error reporting. Disable these three lines before deployment.
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL); 

/*this file is the main connecor and handles data cleaning and issues of login 

*/
//database connection variables
$host= 'localhost';
$user='root';
$usrpassword='';
$database='Company';

//optional for sending SMS via sms.textsms.co.ke API
//chenge these variables to your own for production
$sms_apiKey = "YourAPIKey";
$sms_partnerID = "YourPartinerID";
$sms_shortcode = "TextSMS";


  /* DATABASE CONNECTIONS AS DEFINED IN VARIOUS PAGES*/
        //VARIABLES
       global $connection, $mysqli, $conn;

        //INITIALIZING VARIABLES FOR IMPERATIVE AND OOP

        //for OOP uses
        $mysqli=new mysqli($host,$user,$usrpassword,$database);
        //for imperative
        $conn=mysqli_connect($host,$user,$usrpassword,$database);
        //$connection was the original connector in OOP, same as $conn
       $connection = mysqli_connect($host,$user,$usrpassword,$database); 


      if(!$connection){
        //if connection fails, we abort.
          die("Cannot Establish A Secure Connection To The Host Server At The Moment!");
      }

      try{
        //for PDO
          $db = new PDO('mysql:dbhost='.$host.';dbname='.$database.';charset=utf8',$user,$usrpassword);

      }
      catch(Exception $e){

          die('Cannot Establish A Secure Connection To The Host Server At The Moment!');
      }

      /*DATABASE CONNECTION COMPLETE*/


      /*********************************************************
                  other basic methods
      **********************************************************/

      //function for sending an SMS. I used TextSMS.co.ke API
      function sendSMS($number, $message) 
  {

              // Data to be sent in the POST request
              $postData = [
                      "apikey" => $sms_apiKey,
                      "partnerID" => $sms_partnerID, 
                      "message" => $message,
                      "shortcode" => $sms_shortcode,
                      "mobile" => $number,
                  ];

              // Initialize cURL for making the POST request
              $ch = curl_init("https://sms.textsms.co.ke/api/services/sendsms/");
              curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
              curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($postData));
              curl_setopt($ch, CURLOPT_HTTPHEADER, [
                              'Content-Type: application/json' // Set content type to JSON
              ]);

                          // Execute the request and handle potential errors. use these variables for later tests
              $response = curl_exec($ch); //store response
              $error = curl_error($ch); //store error

              curl_close($ch);  
  }

        //this function is designed to counter sql injection and format the inputs
      function uncrack($data){
        $data=trim($data);
        $data= htmlspecialchars($data);
        $data=stripcslashes($data);

        //replace quotes and forward slashes for SQL
        $data=str_replace('"', '\\"', $data);
        $data=str_replace("'", "\\'", $data);

        return $data;
      };

       //format usernames
    function is_username($data){
      $data=uncrack($data);
      $data=strtolower($data);
      $data=ucwords($data);
      return $data;
    }

     //format emails
    function is_email($data){
      $data=uncrack($data);
      $data=strtolower($data);
      return $data;
    }

    //not so important but it is critical too for temporary autogenerated passwords.
    function random_password() {
        $alphabet = 'abcdefghijklmnopqrstuvwxyz.ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890@%&';
        $pass = array(); //remember to declare $pass as an array
        $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
        for ($i = 0; $i < 8; $i++) {
            $n = rand(0, $alphaLength);
            $pass[] = $alphabet[$n];
        }
        return implode($pass); //turn the array into a string
    }

   
    function is_logged_in_permanent(){
      if (isset($_COOKIE["name"]) && isset($_COOKIE["tsc"]) && isset($_COOKIE["type"])) {
        //set global variables for logged users and return true
        global $uname, $tsc, $type, $funame;

        $uname=$_COOKIE["name"];
        $tsc=$_COOKIE["tsc"];
        $type=$_COOKIE["type"];
        $funame=substr($uname, 0,strpos($uname," "));//first name

        return true;
      }
      else
      { 
        return false;
      }
    }

     function is_logged_in_temporary(){

      if (isset($_SESSION['email'])) {
        //set global variables for logged users and return true
        global $username, $userrole, $userfullname, $connection;

        $email=$_SESSION["email"];
        $username=substr($email, 0,strpos($email,"@"));//user name
        $userrole = isset($_SESSION['role']) ? $_SESSION['role'] : '';
        $userfullname = isset($_SESSION['name']) ? $_SESSION['name'] : $username;

        if ($connection && empty($userrole)) {
          $safeEmail = mysqli_real_escape_string($connection, $email);
          $result = mysqli_query($connection, "SELECT `name`, `role` FROM `admin` WHERE `email`='$safeEmail' LIMIT 1");
          if ($result && mysqli_num_rows($result) === 1) {
            $row = mysqli_fetch_assoc($result);
            $userfullname = $row['name'];
            $userrole = $row['role'];
            $_SESSION['name'] = $userfullname;
            $_SESSION['role'] = $userrole;
          }
        }

        return true;
      }
      else
      { 
        return false;
      }
    }

    function is_admin_user(){
      global $userrole;
      if (empty($userrole)) {
        is_logged_in_temporary();
      }

      return in_array($userrole, ['level-0', 'level-1', 'level-2', 'level-3'], true);
    }

    function is_tenant_user(){
      global $userrole;
      if (empty($userrole)) {
        is_logged_in_temporary();
      }

      return $userrole === 'user';
    }

    function get_logged_in_tenant_record(){
      global $connection;

      if (!is_logged_in_temporary() || !is_tenant_user()) {
        return null;
      }

      $email = isset($_SESSION['email']) ? mysqli_real_escape_string($connection, $_SESSION['email']) : '';
      if ($email === '') {
        return null;
      }

      $queries = [
        "SELECT * FROM `tenantsView` WHERE `email`='$email' AND `tenant_status`='Active' ORDER BY `tenantID` DESC LIMIT 1",
        "SELECT * FROM `tenants` WHERE `email`='$email' AND `tenant_status`='Active' ORDER BY `tenantID` DESC LIMIT 1"
      ];

      foreach ($queries as $sql) {
        $result = @mysqli_query($connection, $sql);
        if ($result && mysqli_num_rows($result) === 1) {
          return mysqli_fetch_assoc($result);
        }
      }

      return null;
    }

    function require_admin_user(){
      if (!is_logged_in_temporary() || !is_admin_user()) {
        header('location:index.php?restricted=1');
        exit();
      }
    }

    function require_tenant_user(){
      if (!is_logged_in_temporary() || !is_tenant_user()) {
        header('location:index.php?restricted=1');
        exit();
      }
    }
?>
